server:
  port: 8089
spring:
  profiles:
    default: default
  application:
    name: order-service
  liquibase:
    url: jdbc:postgresql://localhost:5432/order_db
    change-log: classpath:/db/changelog/db.changelog-master.yml
    password: ${POSTGRESQL_PASSWORD}
    user: ${POSTGRESQL_USERNAME}
  r2dbc:
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    url: r2dbc:postgresql://localhost:5432/order_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
    bootstrap-servers: localhost:9092
    properties:
      spring.json.add.type.headers: false
